### ISSUE TITLE
Excluding doesn't work

### ISSUE THREAD

**Issue by A404M** [ThePBone/MsiEcRamEditor#1]
Line 221 in Form1.cs
It should be 2 instead of 1
Because addresses has 2 digits

**Comment by timschneeb** [comment]
Fixed. f31889d8cd2b3ec8930047348dd3ea2378263c4f

**Comment by timschneeb** [comment]
There was another bug with the exclusion filter. This update fixes it properly: https://github.com/ThePBone/MsiEcRamEditor/releases/tag/v1.4
